### ISSUE TITLE
Code and data release

### ISSUE THREAD

**Issue by Mrsirovo** [isl-org/PhotorealismEnhancement#12]
Hello,

You have done really a great work! 
I really appreciate your contribution!
And, I want to know if there is any promotion in code and data sharing?

Thanks

**Comment by chris-aeviator** [comment]
There's already multiple issues here with the same question.

**Comment by Mrsirovo** [comment]
Yes I know. I want to consult whether there is any progress made. And if possible, when the releash could be published.

**Comment by nbayat** [comment]
There isn't.
When i saw this first i was very excited too, i even unsuccessfully tried to contact them to share my own research with them, until i realized the whole project is a fake.
One thing they don't tell you is that based what i saw on net which i don't know for sure if it was real but very likely to be, this ain't real time processing, a 2 minutes clip will take about an hour to process which is pointless in today's workflow.
I really hope that's not true but for now i kind of gave up.

**Comment by chris-aeviator** [comment]
It’s definitely very strange to not release even after half a year

**Comment by Mrsirovo** [comment]
It's sad to hear about that. But I still hope this fancy project to be true and will have a publish one day.

Than you all a lot!

**Comment by nbayat** [comment]
Me too 😐

Good luck 👍

**Comment by srrichter** [comment]
Hi all,
sorry for the delay in releasing the code. We will release the code as promised and are currently in the final stages of the approval process. I expect this to be done within a few weeks (before the end of the year).

**Comment by chris-aeviator** [comment]
Thanks for your update - I think everybody appreciates your message no matter how long it takes for the release

**Comment by srrichter** [comment]
Thanks for your patience!
