### ISSUE TITLE
Where are the supplementary materials?

### ISSUE THREAD

**Issue by nmynol** [isl-org/PhotorealismEnhancement#13]
Hi, thanks for the nice work! I noticed that you have mentioned the supplementary materials which contain further details on the architecture of the discriminator networks in your paper, but I cannot find them on GitHub or on the Project Website, could you please tell me where I can find them?

**Comment by chris-aeviator** [comment]
The whole repository and the willingness of the team here to commit to releasing their code are a bit 🐟🐠-y - we can only guess why

**Comment by srrichter** [comment]
Hi @nmynol 
thanks for pointing this out. I just added it to the repo. You can find it [here](https://github.com/isl-org/PhotorealismEnhancement/blob/main/paper/supplement.pdf).
