### ISSUE TITLE
GPU memory requirement and dataset size

### ISSUE THREAD

**Issue by georgepsh** [isl-org/PhotorealismEnhancement#15]
Hello, thank you for the provided code!
Could you clarify, please, how much gpu memory the training of your model requires? 
And what was the size of the synthetic dataset you used?

**Comment by srrichter** [comment]
With the full 6 stages of the newer HRNet version it requires more than 11GB (we used 24GB cards). With fewer stages (4 should be ok for decent results) you can push it below the 11GB.
PlayingForData (used for images in the paper) has 25K images of which we used ~20K. The videos were created from the VIPER dataset, of which we trained on ~130K frames.
