### ISSUE TITLE
Question about yaml ?

### ISSUE THREAD

**Issue by D-Mad** [isl-org/PhotorealismEnhancement#23]
i dont undertand about val.txt ,test.txt and train.txt ,How to create this txt file ?
Which paths do i need to change in the yaml file?

**Comment by ZouaghiHoussem** [comment]
you need to create a script to load images and put them in a txt file. then split it as you wish

**Comment by srrichter** [comment]
This is correct. The txt files contain corresponding paths to images, label maps, and gbuffers, each line corresponding to a frame. How you split your dataset into train, val, and test is up to you.
