### ISSUE TITLE
How do I use for GTA 5?

### ISSUE THREAD

**Issue by jonathansmithofficial** [isl-org/PhotorealismEnhancement#28]
I just want to make my gta 5 video have photorealism do I need to code stuff or what wheres the program

**Comment by dailafing** [comment]
Following.
I too would like to know how to get started.

I have a feeling we have to record a video of game play?
And then the realistic video is rendered later.
But if this is a real-time system, that would be incredible.

**Comment by chris-aeviator** [comment]
Have you tried starting with the Setup guide in the code folder?

**Comment by srrichter** [comment]
This is research code for training and testing our method on datasets extracted from games. We do not provide a demo that can be simply run on given videos. The data fed into the algorithm requires recorded G-buffer data, which needs to be obtained from the rendering engine. To start extracting and training a model on your own data, please have a look at the [readme](https://github.com/isl-org/PhotorealismEnhancement/tree/main/code).
