### ISSUE TITLE
Mod

### ISSUE THREAD

**Issue by maxkraft7** [isl-org/PhotorealismEnhancement#3]
At the bottom of the readme you wrote `More coming soon!`. Will there be a mod released? I would love to play GTA that way!

**Comment by chris-aeviator** [comment]
This is scientific research - I guess it's not exactly a mod

**Comment by CasualDev242** [comment]
Yeah, this might not be released as a mod, though I wish they would so people could better appreciate how significant this is. 
This is very impressive, to put it mildly.

**Comment by KCGD** [comment]
well a sort of "mod" may not be impossible, reshade can provide most of the gbuffers necessary to run the AI (at least to what I saw), and the developers claim that it can run at interactive frame rates, implying that it was or could be used in real time. but still we won't know anything untill the code is actually released which is up to the devs

**Comment by CasualDev242** [comment]
Reshade does not have access to the G-buffers, only Depth and Backbuffer. 
On top of that, Reshade does not contain any machine-learning.

The code could be modified by someone savvy to do it, but it would make more sense if Intel released it, rather than reinvent the wheel.

**Comment by srrichter** [comment]
Sorry, a mod is not planned at the moment. Regarding the code release we're thinking of the network architecture, and training and inference code as well as the metric for evaluation.

**Comment by AlexPresso** [comment]
Would be perfect ! this way people could train their own model and modders could implement that model in a mod by themselves

**Comment by honzikv** [comment]
Would love to try this myself, looks very good, though my 1060 would probably die rendering this

**Comment by darthnithin** [comment]
> 
> 
> Would love to try this myself, looks very good, though my 1060 would probably die rendering this

No it wouldn't, (at least not from rendering) the method they use isn't re-rendering the game. They are feeding the output of the game engine into a machine learning model.

**Comment by thijn1234** [comment]
Is it Possible to install this on my own pc?

**Comment by mmtmn** [comment]
Any updates on sharing the code?

**Comment by srrichter** [comment]
There are no plans from our side to create or release a mod. If you create one based on our research code, let us know -- we would love to try it out. The code release is in the final stages of the approval process and I expect to have this done with a few weeks (before the end of the year). Thanks for your patience!

**Comment by dbr2019** [comment]
> 

How is that going?
