### ISSUE TITLE
Custom Robust Label Map

### ISSUE THREAD

**Issue by mvshaag** [isl-org/PhotorealismEnhancement#31]
Hi!

Which dimensions does the perceptual discriminator expect for the robust label map?
Three channel colored segmentation or a single channel ID mapping?

While preparing to train on my custom dataset, I stumbled upon the requirements for the robust label map.  To my understanding, the labels generated by MSeg can be replaced by any arbitrary method of labeling the images. Since I'm training on CityScapes as the target dataset, I thought about replacing the MSeg labels with the City Scapes labels, since they are also available on my synthetic dataset.

I was able to train the model on the three channel segmentation map, but the network seems to generate weird artifacts from time to time (See attached images). I assume they are caused by some error in the robust label map.  Could this be an error on my side, or did you experience similar artifacts during training?

Thank you in advance for any help & insights!

Crops from validation results at step 470000.

![crop_470000_6](https://user-images.githubusercontent.com/42935618/167618822-b50492d2-d8c8-4514-b27a-6e6a1cde9cf3.png)
![crop_470000_1](https://user-images.githubusercontent.com/42935618/167618824-c1bea92b-f6c2-48a4-b166-8fa7044883a2.png)

**Comment by srrichter** [comment]
Hi, 

the robust label map is used here: [ProjectionDiscriminator](https://github.com/isl-org/PhotorealismEnhancement/blob/6936e62a96fc2d913cdd66463d113f7d591d09aa/code/epe/network/discriminators.py#L160). It is expected to be either a single channel int64 with a maximum of [194](https://github.com/isl-org/PhotorealismEnhancement/blob/6936e62a96fc2d913cdd66463d113f7d591d09aa/code/epe/network/discriminators.py#L132) classes or a one-hot-encoded float tensor. 

Even though you have compatible labels, I'd recommend MSeg as it allows you to train on all Cityscapes images, not just the subset that comes with fine-grained annotations.

The artifacts are not necessarili to worry about. Training with an adversarial loss can be unstable and we have seen these as well. They should disappear within some tens of thousand iterations again. If they keep appearing, I'd try to (independently): increase the dataset size, increase the VGG loss, train longer.
