### ISSUE TITLE
Robust label map

### ISSUE THREAD

**Issue by lucamarini22** [isl-org/PhotorealismEnhancement#34]
Hi, what type of files should robust label maps be?

**Comment by EyalMichaeli** [comment]
I used png images and that's ok

**Comment by srrichter** [comment]
Yes, png is fine. The important thing for the labels is that the number of classes corresponds to the [embedding](https://github.com/isl-org/PhotorealismEnhancement/blob/6936e62a96fc2d913cdd66463d113f7d591d09aa/code/epe/network/discriminators.py#L132) in the discriminator.

**Comment by luda1013** [comment]
Hallo Pros,

sorry but i am still stuck at step robust labeling using MSeg. i used the PfD Datasets and Cityscapes.
i am using pretrained weigt for MSeg like in their Colab. But when i did the segmenting for a image folder of PfD, i only got the gray scale images and for 1 image the process took 10 min! so crazy!!

so can i use just the gray scale image for the robust label map?
Thank you very much
