### ISSUE TITLE
You Should Hire Luke Ross... No Idea? Read Why, Here....

### ISSUE THREAD

**Issue by dailafing** [isl-org/PhotorealismEnhancement#4]
I have no affiliation with Luke Ross, I'm just a GTA player.

But the reason I suggest getting in contact with him, is because he has managed to get deep in to the GTA engine, to create a VR mod.

I read a load of information regarding how he was able to achieve this, and from my limited understanding, the things he understands about the game engine, could help you get deeper into the game's engine, allowing faster rendering with those g-buffers. (Which I believe Luke Ross has experience with, to get the VR system to work).

His GitHub name is @LukeRoss00 (ok looks like I cant tag him)... https://github.com/LukeRoss00/ (I hope I'm allowed to to that, forgive me if links aren't allowed.

But yeah, I love the video demonstration, its got me excited to see how this system can be implemented in loads of games.

Like, imagine flight simulator games, paired with a satalite imagery dataset... Slow moving gameplay allows for plenty of time to render stuff...

Truck Simulator games, where the driving style is realistic, and less busy than gta, I'd love that myself since I love just driving around in VR, with a wheel.

Please, I know it's hard, but...... Keep VR in mind.....
Too many developers are brushing off VR, but.... if this became stable, and then VR on top, that would literally be a break through in technological development.... possibly Nobel prise winning, since it really would be a milestone in realtime computer generated photorealism....

Also, can we keep multi gpu support in mind? Because I would quite happily fork out for x4 3090 cards, if the software could benefit from multiple cards... Would multiple cards be able to get that half a second render time, down to a quarter, or an 8th?

**Comment by AlexPresso** [comment]
I don't know anything about VR dev but I think the VR mod from LukeRoss would work in any case since the AI trained model would only change how textures are rendered, not the player camera / double cameras (in case of VR) behavior

**Comment by KCGD** [comment]
I think that they mean is that if @LukeRoss00 was able to get deep enough in GTA's engine to make a VR mod, maybe they could find a way to get access to the gbuffers and make this into a mod

**Comment by IceHacks** [comment]
I don't think this is meant to be a mod. But maybe whoever you are talking about could take this network and implement it into one. I seriously doubt Intel itself would venture into modding.

**Comment by darthnithin** [comment]
This is not meant to be a mod, this is a research paper, the point is that when the research is good, _you_ (or someone else) could make a mod based on this underlying research.

**Comment by srrichter** [comment]
Hi,
thanks for the great suggestions and comments. I confirm that this is a research project and we have currently no plans to turn this into a mod. If you turn it into one or know someone who did, let us know - we'd love to try it out.
