### ISSUE TITLE
How many images should I input?

### ISSUE THREAD

**Issue by lzdnsb** [isl-org/PhotorealismEnhancement#40]
Thank you for the great work, really inspiring!

In readme, the only limitation of input is the matched_crops_PfD-Cityscapes.csv should contain at least 200K pairs (lines), more is better. I used 2000 images from Playing for Data dataset and 1703 images from Cityscapes dataset, and I get 230k pairs, which is enough.

My question is:
Should I use same number of images from Playing for Data dataset and Cityscapes dataset?

**Comment by srrichter** [comment]
The number does not need to be the same for the different datasets. But I suspect that 2000 images is way too small to get consistent results. For the still images (Playing For Data), we used 20K images, for the videos we used a subset of VIPER on the synthetic side, and all of Cityscapes (coarse and fine) on the real side. With fewer images you will likely get artifacts in many images (alternatively you can increase the VGG-loss, but then the modifications will be smaller)
