### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LuanDalOrto** [isl-org/PhotorealismEnhancement#41]
Hi, my name is Luan I would like to know how I can use this AI Code to turn CGI Video or Photo to 
Photorealism Enhancement with subjects like Humans and Animals with and without fur, to reach a more realistic video.Thank You Sir,Best, Luan Dal Orto Vaz.

**Comment by srrichter** [comment]
Hi,
You'll need a large set of synthetic images and real images with similar content. For the synthetic images, you'll also need G-Buffers encoding geometry, material, and lighting information. To work with video, I'd recommend at the order of at least 20K images for synthetic and real content, the more the better.

**Comment by LuanDalOrto** [comment]
Hi,Thank you. there is a Tutorial that I can follow? Thank You Sir Best
Wishes,Luan Dal Orto Vaz.

Em qua., 26 de out. de 2022 às 17:03, srrichter ***@***.***>
escreveu:
