### ISSUE TITLE
Sigmoid missing in hr_new?

### ISSUE THREAD

**Issue by KacperKazan** [isl-org/PhotorealismEnhancement#45]
Hello, I've noticed that when using the hr_new network the rec_fake (output of the generator) seems to have an unbounded value range. Compared to the loaded fake and real image which have pixels values bounded between [0, 1]

https://github.com/isl-org/PhotorealismEnhancement/blob/6936e62a96fc2d913cdd66463d113f7d591d09aa/code/epe/EPEExperiment.py#L204-L209

The 'hr' option uses the **ResidualGenerator** which uses a sigmoid on the output to bound the output between [0, 1]
https://github.com/isl-org/PhotorealismEnhancement/blob/6936e62a96fc2d913cdd66463d113f7d591d09aa/code/epe/network/generator.py#L4-L6

However the **PassthruGenerator** which 'hr_new' uses doesn't have any sigmoid on the output. 

Is this a bug? since it seems that the output image should be bounded [0,1] just as the real image is

**Comment by srrichter** [comment]
We removed the sigmoid in the updated version since it seemed not to be necessary with the setup we ran. If you're playing with different datasets or are facing issues with larger values, including the sigmoid is a good idea.
