### ISSUE TITLE
Can't figure out how to compile it. 

### ISSUE THREAD

**Issue by Charles1192** [isl-org/PhotorealismEnhancement#47]
Genuinely would pay money for someone to send me precompiled code

**Comment by KacperKazan** [comment]
What do you mean? it's python.. it doesn't compile

Follow the setup instructions here
https://github.com/isl-org/PhotorealismEnhancement/tree/main/code#setup
First create the [conda](https://docs.conda.io/en/latest/miniconda.html) environment then install the packages listed

then install the MSeg, faiss, LPIPS and Korina (each of those projects has instructions how to install as well)

**Comment by char119** [comment]
> Genuinely would pay money for someone to send me precompiled code

Why don't you just set it up like how they said bro
