### ISSUE TITLE
How to get the ground truth label map of GTA game?

### ISSUE THREAD

**Issue by D-Mad** [isl-org/PhotorealismEnhancement#48]

**Comment by srrichter** [comment]
We worked with the [http://download.visinf.tu-darmstadt.de/data/from_games/](Playing for data) and [https://playing-for-benchmarks.org/](Playing for benchmark) datasets. For your own captures, you'll likely need to create your own annotations. You can use [https://bitbucket.org/visinf/projects-2016-playing-for-data](this code) for that (keep in mind that the ground truth labels don't need to match fine-grained semantic classes, but rather coarsely different material types (like vegetation, road, sky, vehicles).
