### ISSUE TITLE
Loading model for training

### ISSUE THREAD

**Issue by lucamarini22** [isl-org/PhotorealismEnhancement#49]
Hi, is there a way to load an existing trained model (trained with this same repository) to not restart training from scratch?

**Comment by lucamarini22** [comment]
I think I already solved this by specifying the property `name_load` also in the config file of training

**Comment by luda1013** [comment]
Hallo @lucamarini22 , so are there or did they give us the pretrained weight they use for this repo? if yea, where i can test it directly?

o ya,i have also question, can we edit the g-buffer parameter or introducing new parameter for the pretrained weight? thank you very much
