### ISSUE TITLE
RuntimeError while training 

### ISSUE THREAD

**Issue by sandip824** [isl-org/PhotorealismEnhancement#51]
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 196, W: 0) output (H: 13, W: 13)

any idea what could be the possible reason ?

**Comment by Sevar-Sheer** [comment]
Hello @sandip824 ,
Have you come up with a solution to this issue?

**Comment by sandip824** [comment]
issue was with the our custom robust label maps , maximum 194 classes was allowed , I updated the our custom robust labels accordingly and it worked.
