### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wangjksjtu** [isl-org/PhotorealismEnhancement#58]
Thanks for your amazing works!! Could you please add the License file for this project, thanks so much!

**Comment by czero69** [comment]
Hey, seems license is not added to the github license field, but It can be found here:
https://github.com/isl-org/PhotorealismEnhancement/blob/main/code/LICENSE
its MIT License

**Comment by wangjksjtu** [comment]
Get it, Thanks so much!!
