### ISSUE TITLE
Reversing the input and output

### ISSUE THREAD

**Issue by alpkabac** [isl-org/PhotorealismEnhancement#6]
I could not find how to contact you direclty, and issues are not the place for this, but I was really curious if we could reverse the process. What I mean by that is if we used photorealistic images as the input, could convert them into much cartoony or fictional(?) ones?

**Comment by IceHacks** [comment]
I would assume it to be much the same process. Just use GTA pictures at the "Real Image" and the data used in the "G-Buffer Encoder."

**Comment by imfunniee** [comment]
ye similar

**Comment by darthnithin** [comment]
> 
> 
> I would assume it to be much the same process. Just use GTA pictures at the "Real Image" and the data used in the "G-Buffer Encoder."
I assume for the dataset you would just use the game engine (GTA) pictures, and the real images as input, though you might have to annotate the images as i dont see how you could get the G-Buffer (which would come from an engine) from real pictures.

**Comment by srrichter** [comment]
That's a great idea. I guess a good way to start would be even without the G-buffers here. Our experiments indicated that you can get strong results even without the G-buffers.
