### ISSUE TITLE
beta version?

### ISSUE THREAD

**Issue by mrwal3** [isl-org/PhotorealismEnhancement#7]
Hi Guys,

I'm a 3d artist, I'd love to test this out on some of my work, is there going to be a beta version released? Cheers.

**Comment by chris-aeviator** [comment]
This is scientific A.I. research - not a product, guess you'll need some python skills once it comes out in order to do something with it.

**Comment by mrwal3** [comment]
Thanks for the tip, I work with a coding guy so we will give it a go and see what we can come up with, cheers.

**Comment by darthnithin** [comment]
[#3](https://github.com/intel-isl/PhotorealismEnhancement/issues/3#issuecomment-843573226)

**Comment by srrichter** [comment]
Hi,
confirming @chris-aeviator 's comments -- the code release is for the scientific project. It's Python based, and will likely require some work to adapt it to other projects.
